export const QUERY_KEYS = {
  /* Organization */
  ORGANIZATION_LIST: 'ORGANIZATION_LIST',
  ORGANIZATION_DETAIL: 'ORGANIZATION_DETAIL',

  /* User */
  USER_LIST: 'USER_LIST',
  USER_DETAIL: 'USER_DETAIL',

  /* News */
  NEWS_LIST: 'NEWS_LIST',

  /* Organization Role */
  ORGANIZATION_ROLE_LIST: 'ORGANIZATION_ROLE_LIST',

  /* Client */
  CLIENT_LIST: 'CLIENT_LIST',

  /* Product */
  PRODUCT_LIST: 'PRODUCT_LIST',

  /* QR Code */
  QR_CODE_LIST: 'QR_CODE_LIST',

  /* Data Table */
  DATA_TABLE_LIST: 'DATA_TABLE_LIST',
};
