version: "3.8"

services:
  hrm-app:
    build:
      context: ./application
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
